/*******************create library and sort data by subject*********************/                                                                                                                                                                                          
libname hi 'C:\Users\Shaocheng Peng\Desktop\Biosmetrics Computing\project II';                                                                                                                                                                                  
proc sort data = hi.BP out = bp;                                                                                                                                                                                                                                
by subject;                                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc sort data = hi.Demog out = demog;                                                                                                                                                                                                                          
by subject;                                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc sort data = hi.Glucose out = glucose;                                                                                                                                                                                                                      
by subject;                                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc sort data = hi.hw out = hw;                                                                                                                                                                                                                                
by subject;                                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc sort data = hi.lipid out = lipid;                                                                                                                                                                                                                          
by subject;                                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc sort data = hi.misc out = misc;                                                                                                                                                                                                                            
by subject;                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                
/******************merge and combine**********/                                                                                                                                                                                                                 
/*****************criteria***************/                                                                                                                                                                                                                      
data hi.combine;                                                                                                                                                                                                                                                
merge bp demog glucose hw lipid misc;                                                                                                                                                                                                                           
by subject;                                                                                                                                                                                                                                                     
age=(doe-dob)/365.25;                                                                                                                                                                                                                                           
format age 5.2;                                                                                                                                                                                                                                                 
if first.subject;                                                                                                                                                                                                                                               
if         gender = 'F' THEN sex = 1;                                                                                                                                                                                                                           
else                         sex = 0;                                                                                                                                                                                                                           
if glucose >= 120       Then glucose_status = 1;                                                                                                                                                                                                                
else                         glucose_status = 0;                                                                                                                                                                                                                
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
data two;                                                                                                                                                                                                                                                       
set hi.combine;                                                                                                                                                                                                                                                 
run;                                                                                                                                                                                                                                                            
/********check combined datasets******/                                                                                                                                                                                                                                                              
proc means data = two;                                                                                                                                                                                                                                          
title 'combine means';                                                                                                                                                                                                                                          
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc print data = two(obs = 5);                                                                                                                                                                                                                                 
title 'combinedata';                                                                                                                                                                                                                                            
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
/*                  
Is diff means the variable is different between group that has chd and group doesn't have
No diff means there is no difference between two groups                                                                                                                                                                                                                                            
                     chd                    categorical         response                                                                                                                                                                                                
                     dbp                    categorical         ok is diff                                                                                                                                                                                               
                     sbp                    categorical         ok is diff                                                                                                                                                                                               
                     site                   categorical         ok is diff                                                                                                                                                                                      
                     gender                 categorical         ok no diff                                                                                                                                                                                      
                     smoke                  categorical         ok no diff                                                                                                                                                                                      
                     drink                  categorical         ok no diff                                                                                                                                                                                      
                     marital                categorical         ok no diff                                                                                                                                                                                      
                     education              categorical         ok no diff                                                                                                                                                                                      
                     glucose_status         categorical         ok is diff                                                                                                                                                                                      
                     pregnancy              categorical         ok is diff                                                                                                                                                                                      
                     exercise               categorical         ok no diff                                                                                                                                                                                      
                     age                    numeric             ok is diff                                                                                                                                                                                     
                     height                 numeric             ok no diff                                                                                                                                                                                     
                     weight                 numeric             ok no diff                                                                                                                                                                                     
                     hdl                    numeric             ok is diff                                                                                                                                                                                     
                     ldl                    numeric             ok is diff                                                                                                                                                                                     
                     tg                     numeric             ok is diff                                                                                                                                                                                     
                     tc                     numeric             ok is diff                                                                                                                                                                                     
                     glucose                numeric             ok is diff                                                                                                                                                                                     
                     dbp                    numeric             ok is diff                                                                                                                                                                                     
                     sbp                    numeric             ok is diff                                                                                                                                                                                     
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
*/                                                                                                                                                                                                                                                              
/**********************************format process***************************/                                                                                                                                                                                   
proc format;                                                                                                                                                                                                                                                    
value site_name 1 = 'AZ'                                                                                                                                                                                                                                        
                2 = 'CA'                                                                                                                                                                                                                                        
                3 = 'NJ'                                                                                                                                                                                                                                        
                4 = 'NY'                                                                                                                                                                                                                                        
                5 = 'TX'                                                                                                                                                                                                                                        
;                                                                                                                                                                                                                                                               
value gender_name 1 = 'Female'                                                                                                                                                                                                                                  
                  0 = 'Male'                                                                                                                                                                                                                                    
;                                                                                                                                                                                                                                                               
value smoke_name 0 = 'Non-smoker'                                                                                                                                                                                                                               
                 1 = 'Smoker'                                                                                                                                                                                                                                   
;                                                                                                                                                                                                                                                               
value drink_name 1 = 'Never'                                                                                                                                                                                                                                    
                 2 = '<1 per week'                                                                                                                                                                                                                              
                 3 = '1-3 per week'                                                                                                                                                                                                                             
                 4 = '4-6 per week'                                                                                                                                                                                                                             
                 5 = 'one more per day'                                                                                                                                                                                                                         
;                                                                                                                                                                                                                                                               
value marital_name  1 = 'Married'                                                                                                                                                                                                                               
                    2 = 'Single'                                                                                                                                                                                                                                
                    3 = 'Divorced'                                                                                                                                                                                                                              
                    4 = 'Other'                                                                                                                                                                                                                                 
;                                                                                                                                                                                                                                                               
value education_name 1 = 'Below high school'                                                                                                                                                                                                                    
                     2 = 'High school'                                                                                                                                                                                                                          
                     3 = 'College'                                                                                                                                                                                                                              
                     4 = 'Post-college'                                                                                                                                                                                                                         
;                                                                                                                                                                                                                                                               
value glucose_status_name 0 = 'normal'                                                                                                                                                                                                                          
                          1 = 'high_glucose_risk'                                                                                                                                                                                                               
;                                                                                                                                                                                                                                                               
value pregnancy_name 0 = 'No'                                                                                                                                                                                                                                   
                     1 = 'Yes'                                                                                                                                                                                                                                  
;                                                                                                                                                                                                                                                               
value exercise_name 0 = 'not routinely past 3 month'                                                                                                                                                                                                            
                    1 = 'routinely past 3 month'                                                                                                                                                                                                                
;                                                                                                                                                                                                                                                               
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
/***************************************discrete variable*****************************************/                                                                                                                                                             
*whether there is difference between smokers and non-smokers with respect to the heart attack;                                                                                                                                                                  
                                                                                                                                                                                                                                                                
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*smoke / CHISQ EXPECTED;                                                                                                                                                                                                                           
format smoke smoke_name.;                                                                                                                                                                                                                                       
   TITLE 'freq chd&smoke';                                                                                                                                                                                                                                      
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
*whether there is difference between drink status with respect to the heart attack;                                                                                                                                                                             
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*drink / CHISQ EXPECTED;                                                                                                                                                                                                                           
format drink drink_name.;                                                                                                                                                                                                                                       
   TITLE 'freq chd&drink';                                                                                                                                                                                                                                      
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
*whether there is difference between marital status with respect to the heart attack;                                                                                                                                                                           
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*marital / CHISQ EXPECTED;                                                                                                                                                                                                                         
format marital marital_name.;                                                                                                                                                                                                                                   
   TITLE 'freq chd&marital';                                                                                                                                                                                                                                    
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
*whether there is difference between education status with respect to the heart attack;                                                                                                                                                                         
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*education / CHISQ EXPECTED;                                                                                                                                                                                                                       
format education education_name.;                                                                                                                                                                                                                               
   TITLE 'freq chd&education';                                                                                                                                                                                                                                  
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
*whether there is difference between glucose status with respect to the heart attack;                                                                                                                                                                           
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*glucose_status / CHISQ EXPECTED;                                                                                                                                                                                                                  
format glucose_status glucose_status_name.;                                                                                                                                                                                                                     
   TITLE 'freq chd&glucose_status';                                                                                                                                                                                                                             
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
*whether there is difference between pregnancy status with respect to the heart attack;                                                                                                                                                                         
*pregnancy = 9 means the observations are fail to answer the question, which is not appropriate to count for the results,                                                                                                                                       
so we first excluded those observations, and then did the analysis;                                                                                                                                                                                             
data pregnancy;                                                                                                                                                                                                                                                 
set two;                                                                                                                                                                                                                                                        
if pregnancy = 9 THEN delete;                                                                                                                                                                                                                                   
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC FREQ DATA=pregnancy;                                                                                                                                                                                                                                       
   TABLES chd*pregnancy / CHISQ EXPECTED;                                                                                                                                                                                                                       
format pregnancy pregnancy_name.;                                                                                                                                                                                                                               
   TITLE 'freq chd&pregnancy';                                                                                                                                                                                                                                  
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
*whether there is difference between exercise status with respect to the heart attack;                                                                                                                                                                          
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*exercise / CHISQ EXPECTED;                                                                                                                                                                                                                        
format exercise exercise_name.;                                                                                                                                                                                                                                 
   TITLE 'freq chd&exercise';                                                                                                                                                                                                                                   
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
*whether there is difference between different sites with respect to the heart attack;                                                                                                                                                                          
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*site / CHISQ EXPECTED;                                                                                                                                                                                                                            
format site site_name.;                                                                                                                                                                                                                                         
   TITLE 'freq chd&site';                                                                                                                                                                                                                                       
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
*whether there is difference between different gender with respect to the heart attack;                                                                                                                                                                         
PROC FREQ DATA=two;                                                                                                                                                                                                                                             
   TABLES chd*sex / CHISQ EXPECTED;                                                                                                                                                                                                                             
format sex gender_name.;                                                                                                                                                                                                                                        
   TITLE 'freq chd&gender';                                                                                                                                                                                                                                     
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
/************************continuous variable**********************/      
/******most are not normally distributed, use the wilcoxon signed rank test******/                                                                                                                                                                                      
PROC univariate data = two normal;                                                                                                                                                                                                                              
var age;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'univariate_age&chd';                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var age;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon age&chd';                                                                                                                                                                                                                                       
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var height;                                                                                                                                                                                                                                                     
class chd;                                                                                                                                                                                                                                                      
title 'univariate_height&chd';                                                                                                                                                                                                                                  
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var height;                                                                                                                                                                                                                                                     
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon height&chd';                                                                                                                                                                                                                                    
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var weight;                                                                                                                                                                                                                                                     
class chd;                                                                                                                                                                                                                                                      
title 'univariate_weight&chd';                                                                                                                                                                                                                                  
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var weight;                                                                                                                                                                                                                                                     
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon weight&chd';                                                                                                                                                                                                                                    
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var hdl;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'univariate_hdl&chd';                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var hdl;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon hdl&chd';                                                                                                                                                                                                                                       
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var ldl;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'univariate_ldl&chd';                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var ldl;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon ldl&chd';                                                                                                                                                                                                                                       
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var tg;                                                                                                                                                                                                                                                         
class chd;                                                                                                                                                                                                                                                      
title 'univariate_tg&chd';                                                                                                                                                                                                                                      
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var tg;                                                                                                                                                                                                                                                         
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon tg&chd';                                                                                                                                                                                                                                        
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var tc;                                                                                                                                                                                                                                                         
class chd;                                                                                                                                                                                                                                                      
title 'univariate_tc&chd';                                                                                                                                                                                                                                      
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var tc;                                                                                                                                                                                                                                                         
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon tc&chd';                                                                                                                                                                                                                                        
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var glucose;                                                                                                                                                                                                                                                    
class chd;                                                                                                                                                                                                                                                      
title 'univariate_glucose&chd';                                                                                                                                                                                                                                 
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var glucose;                                                                                                                                                                                                                                                    
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon glucose&chd';                                                                                                                                                                                                                                   
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
proc univariate data = two normal;                                                                                                                                                                                                                              
var dbp;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'univariate_dbp&chd';                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var dbp;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon dbp&chd';                                                                                                                                                                                                                                       
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC univariate data = two normal;                                                                                                                                                                                                                              
var sbp;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'univariate_sbp&chd';                                                                                                                                                                                                                                     
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC NPAR1WAY DATA=two WILCOXON;                                                                                                                                                                                                                                
var sbp;                                                                                                                                                                                                                                                        
class chd;                                                                                                                                                                                                                                                      
title 'wilcoxon sbp&chd';                                                                                                                                                                                                                                       
run;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
/******logistic regression, choosing every variables that are different between groups of individuals who had chd and who hadn't******/                                                                                                                                                                                                                                                                
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                                                                                      
                   / SELECTION=FORWARD DETAILS;                                                                                                                                                                                                                 
   TITLE 'Logistic regression with forward selection: using default thresholds';                                                                                                                                                                                
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                                                                                      
                   / SELECTION=BACKWARD DETAILS;                                                                                                                                                                                                                
   TITLE 'Logistic regression with backward selection: using default thresholds';                                                                                                                                                                               
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                                                                                      
                   / SELECTION=STEPWISE DETAILS;                                                                                                                                                                                                                
   TITLE 'Logistic regression with stepwise selection: using default thresholds';                                                                                                                                                                               
RUN;    

                                                                                                                                                                                                                                                        
/******logistic regression, choosing all of the variables in the combined dataset******/                                                                                                                                                                                                                                                                 
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = SMOKE DRINK SEX EDUCATION MARITAL HEIGHT WEIGHT EXERCISE site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                             
                   / SELECTION=FORWARD DETAILS;                                                                                                                                                                                                                 
   TITLE 'Logistic regression with forward selection: using default thresholds';                                                                                                                                                                                
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = SMOKE DRINK SEX EDUCATION MARITAL HEIGHT WEIGHT EXERCISE site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                             
                   / SELECTION=BACKWARD DETAILS;                                                                                                                                                                                                                
   TITLE 'Logistic regression with backward selection: using default thresholds';                                                                                                                                                                               
RUN;                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                
PROC LOGISTIC DATA=two;                                                                                                                                                                                                                                         
   MODEL chd(EVENT='1') = SMOKE DRINK SEX EDUCATION MARITAL HEIGHT WEIGHT EXERCISE site pregnancy hdl ldl tg tc glucose dbp sbp age                                                                                                                             
                   / SELECTION=STEPWISE DETAILS;                                                                                                                                                                                                                
   TITLE 'Logistic regression with stepwise selection: using default thresholds';                                                                                                                                                                               
RUN;
